version: '3'

services:
  db:
    image: mariadb
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED -binlog-format=ROW
    restart: always
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - db.env
    networks:
      nextcloud:
        aliases:
          - mariadb

  redis:
    image: redis
    container_name: nextcloud-redis
    restart: always
    networks:
      nextcloud:
        aliases:
          - redis

  nextcloud:
    build: ./app
    container_name: nextcloud-app
    restart: always
    ports:
      - "8081:80"
    volumes:
      - nextcloud-app:/var/www/html
    environment:
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

  cron:
    build: ./app
    container_name: nextcloud-cron
    restart: always
    volumes:
      - nextcloud-app:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - nextcloud

volumes:
  nextcloud-db:
  nextcloud-app:


networks:
  nextcloud:
