version: "3"

services:
    nextcloud-web:
        container_name: nextcloud-web
        image: nextcloud:13.0
        volumes:
            - nextcloud-web-data:/var/www/html
        depends_on: 
            - nextcloud-db
        ports:
            - "80:80"
        environment:
            MYSQL_DATABASE: nextcloud
            MYSQL_USER    : nextcloud
            MYSQL_PASSWORD: nextcloud
            MYSQL_HOST    : nextcloud-db
            NEXTCLOUD_TRUSTED_DOMAINS: "localhost"
        networks:
            nextcloud-net:
                aliases:
                    - nextcloud-web

    nextcloud-db:
        container_name: nextcloud-db
        image: mysql:5.7
        volumes:
            - nextcloud-db-data:/var/lib/mysql
        restart: always
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_DATABASE:             nextcloud
            MYSQL_USER:                 nextcloud
            MYSQL_PASSWORD:             nextcloud
        networks:
            nextcloud-net:
                aliases:
                    - nextcloud-db

volumes:
    nextcloud-db-data:
    nextcloud-web-data:
networks:
    nextcloud-net:
