version: '3'

services:
    app:
        image: nextcloud:16.0.1-fpm-alpine
        container_name: nextcloud_app
        restart: always
        volumes:
            - nextcloud_app:/var/www/html
        env_file:
            - ./mysql.env
            - ./app.env
        networks:
            nextcloud:
                aliases:
                    - app
        depends_on:
            - mariadb
            - redis

    cron:
        image: nextcloud:16.0.1-fpm-alpine
        container_name: nextcloud_cron
        restart: always
        volumes:
            - nextcloud_app:/var/www/html
        entrypoint: /cron.sh
        depends_on:
            - mariadb
            - redis

    web:
        image: nginx:1.17-alpine
        container_name: nextcloud_web
        restart: always
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - nextcloud_app:/var/www/html:ro
            - /path/to/fullchain.pem:/etc/ssl/nginx/fullchain.pem
            - /path/to/privkey.pem:/etc/ssl/nginx/privkey.pem
        ports:
            - "80:80"
            - "443:443"
        networks:
            - nextcloud
        depends_on:
            - app


    mariadb:
        image: mariadb:10.4.5
        container_name: nextcloud_db
        command: --transaction-isolation=READ-COMMITTED -binlog-format=ROW
        restart: always
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD="yes"
        env_file:
            - ./mysql.env
        networks:
            nextcloud:
                aliases:
                    - mariadb

    redis:
        image: redis:5.0.5-alpine
        container_name: nextcloud_cache
        restart: always
        networks:
            nextcloud:
                aliases:
                    - redis

volumes:
    nextcloud_app:
networks:
    nextcloud:
