version: "3"

services:
  bot:
    container_name: efb_master
    build: .
    volumes:
      - profiles:/root/.ehforwarderbot/profiles
    networks:
      - cfb
    depends_on:
      - cqhttp

  cqhttp:
    container_name: efb_slave_qq
    image: "richardchien/cqhttp"
    networks:
      cfg:
        aliases:
          - cq
    environment:
      - COOLQ_PORT=5700
      - VNC_PASSWORD=123456
      - CQHTTP_POST_URL=http://bot:8000
      - COOLQ_ACCOUNT=987407909
      - CQHTTP_ACCESS_TOKEN=ac0f790e1fb74ebcaf45da77a6f9de47
      - CQHTTP_POST_MESSAGE_FORMAT=array
      - FORCE_ENV=true
    ports:
      - "9801:9000"

networks:
  efb:
