version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: monitor_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: "https://grafana.server.name"
      GF_SECURITY_ADMIN_PASSWORD: "secret"
    networks:
      - monitor_net
    volumes:
      - monitor_grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    container_name: monitor_prometheus
    restart: always
    networks:
      monitor_net:
        aliases:
          - prom
    volumes:
      - ./prometheus:/etc/prometheus


volumes:
  monitor_grafana:


networks:
  monitor_net:
